services:
  vulnerable-web:
    image: nginx:latest
    container_name: vulnerable-web
    privileged: false
    network_mode: bridge
    pid: ""
    user: "1000:1000"
    restart: always
    environment:
      - ADMIN_USERNAME=admin
      - DB_HOST=insecure-db
      - DB_USER=vulnuser
      # пароль — через .env/secret, а не в явном виде
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backup:/var/backups:rw
    cap_drop: ["ALL"]
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs: ["/tmp"]

  debug-shell:
    image: alpine:latest
    container_name: debug-shell
    privileged: false
    network_mode: bridge
    user: "1000:1000"
    cap_drop: ["ALL"]
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs: ["/tmp"]
    command: ["sh", "-c", "sleep infinity"]
